defaults:
  - _self_
  - task: openwebtext_gpt2
  - device: gpu
  - hydra: default

seed: 27
save_dir: "runs/"

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  project: "LM-GFN-next-sentence-${task.name}"
  save_dir: ${save_dir}
  offline: False